#!name=sfacg
#!desc=sfacg
[Script]
sfacg_cookie=type=http-response,pattern=^http[s]?:\/\/api\.sfacg\.com\/user\/tickets,requires-body=0,script-path=https://raw.githubusercontent.com/ztmzzz/scripts/master/shadowrocket/sfacg/sfacg.cookie.js
sfacg = type=cron,script-path=https://raw.githubusercontent.com/ztmzzz/scripts/master/shadowrocket/sfacg/sfacg.js,cronexpr="5 1-23/2 * * *"
[MITM]
hostname= %APPEND% api.sfacg.com
